### ISSUE TITLE
RuntimeError: Bad password for file for correct password

### ISSUE THREAD

**Issue by zdenop** [danifus/pyzipper#10]
I got error message:

```
C:\Program Files\Python38\lib\site-packages\pyzipper\zipfile_aes.py in __init__(self, zinfo, pwd, encryption_header)
     53         encpwdverify = keymaterial[2*key_length:]
     54         if encpwdverify != pwd_verify:
---> 55             raise RuntimeError("Bad password for file %r" % zinfo.filename)
     56 
     57         enckey = keymaterial[:key_length]

RuntimeError: Bad password for file 'export_SK0602000000001719741357_22-07-2020-22-07-2020.XML'
```

my code is:

``` python
with pyzipper.AESZipFile(zip_filename) as zf:
    zf.setpassword(secret_password)
    zf.setencryption(pyzipper.WZ_AES, nbits=256)
    print(zf.infolist())
    my_secrets = zf.read(zf.namelist()[0])
```

zf.infolist() ouput is: `[<AESZipInfo filename='export_SK0602000000001719741357_22-07-2020-22-07-2020.XML' compress_type=deflate file_size=221316 compress_size=4970>]`

But I can extract this file with `7z` using the same password. 
BTW: `7p l -slt` produced this info:
```
----------
Path = export_SK0602000000001719741357_16-07-2020-16-07-2020.XML
Folder = -
Size = 244034
Packed Size = 5214
Modified = 2020-07-17 03:49:56
Created =
Accessed =
Attributes =
Encrypted = +
Comment =
CRC =
Method = AES-256 Deflate
Characteristics = WzAES : Encrypt
Host OS = FAT
Version = 20
Volume Index = 0
Offset = 0
```

I use python 3.8.5 64bit on Windows 10 and pyzipper 0.3.3

**Comment by danifus** [comment]
Hi zdenop,

I'm having trouble recreating this error locally. What program was used to generate that file? Do any other files from this source work with pyzipper?

The file in the error (`export_SK0602000000001719741357_22-07-2020-22-07-2020.XML`) is different to the file used with `7z l -slt`(`export_SK0602000000001719741357_16-07-2020-16-07-2020.XML`). Is that of any significance?

**Comment by zdenop** [comment]
Difference is coming for other file from the same provider. I do not know, how file was generated.
If needed I can send you files and password by email.

**Comment by danifus** [comment]
What is the output for `7z l -slt` for the file that failed? Or did both of them fail?

It is possible that the password check is failing (a short cut to test if the password is correct before decrypting the entire file) but the file can still be extracted. Below is some modifications to AESZipFile so that it will continue to try and extract the file even if the preliminary password check fails:

```
import struct

import pyzipper
from pyzipper.zipfile_aes import (
    WZ_AES,
    WZ_KEY_LENGTHS,
    WZ_SALT_LENGTHS,
    AES,
    Counter,
    HMAC,
    SHA1Hash,
    PBKDF2,
    AESZipDecrypter,
    AESZipExtFile,
    AESZipFile,
)


class AESZipDecrypterNoPwordCheck(AESZipDecrypter):

    def __init__(self, zinfo, pwd, encryption_header):
        self.filename = zinfo.filename

        key_length = WZ_KEY_LENGTHS[zinfo.wz_aes_strength]
        salt_length = WZ_SALT_LENGTHS[zinfo.wz_aes_strength]

        salt = struct.unpack(
            "<{}s".format(salt_length),
            encryption_header[:salt_length]
        )[0]
        pwd_verify_length = 2
        pwd_verify = encryption_header[salt_length:]
        dkLen = 2*key_length + pwd_verify_length
        keymaterial = PBKDF2(pwd, salt, count=1000, dkLen=dkLen)

        encpwdverify = keymaterial[2*key_length:]
        # if encpwdverify != pwd_verify:
        #     raise RuntimeError("Bad password for file %r" % zinfo.filename)

        enckey = keymaterial[:key_length]
        self.decypter = AES.new(
            enckey,
            AES.MODE_CTR,
            counter=Counter.new(nbits=128, little_endian=True)
        )
        encmac_key = keymaterial[key_length:2*key_length]
        self.hmac = HMAC.new(encmac_key, digestmod=SHA1Hash())


class AESZipExtFileNoPwordCheck(AESZipExtFile):

    def setup_aeszipdecrypter(self):
        if not self._pwd:
            raise RuntimeError(
                'File %r is encrypted with %s encryption and requires a '
                'password.' % (self.name, WZ_AES)
            )
        encryption_header_length = AESZipDecrypterNoPwordCheck.encryption_header_length(
            self._zinfo)
        self.encryption_header = self._fileobj.read(encryption_header_length)
        # Adjust read size for encrypted files since the start of the file
        # may be used for the encryption/password information.
        self._orig_compress_left -= encryption_header_length
        # Also remove the hmac length from the end of the file.
        self._orig_compress_left -= AESZipDecrypterNoPwordCheck.hmac_size

        return AESZipDecrypterNoPwordCheck


class AESZipFileNoPwordCheck(AESZipFile):
    zipextfile_cls = AESZipExtFileNoPwordCheck
```

Are you able to put the above in a script and use `AESZipFileNoPwordCheck` defined here instead of `AESZipFile` on your file?

**Comment by zdenop** [comment]
I have problem with all zip files (daily statements) I received from this source. `7z l -slt export_SK0602000000001719741357_22-07-2020-22-07-2020.ZIP` produce this:

```cmd
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 5204 bytes (6 KiB)

Listing archive: export_SK0602000000001719741357_22-07-2020-22-07-2020.ZIP

--
Path = export_SK0602000000001719741357_22-07-2020-22-07-2020.ZIP
Type = zip
Physical Size = 5204

----------
Path = export_SK0602000000001719741357_22-07-2020-22-07-2020.XML
Folder = -
Size = 221316
Packed Size = 4970
Modified = 2020-07-23 03:12:52
Created =
Accessed =
Attributes =
Encrypted = +
Comment =
CRC =
Method = AES-256 Deflate
Characteristics = WzAES : Encrypt
Host OS = FAT
Version = 20
Volume Index = 0
Offset = 0
```

AESZipFileNoPwordCheck run as this:

```python
with AESZipFileNoPwordCheck(zip_filename) as zf:
    zf.setpassword(secret_password)
    zf.setencryption(pyzipper.WZ_AES, nbits=256)
    print(zf.infolist())
    my_secrets = zf.read(zf.namelist()[0])
```
produces this:

```sh
[<AESZipInfo filename='export_SK0602000000001719741357_22-07-2020-22-07-2020.XML' compress_type=deflate file_size=221316 compress_size=4970>]
Traceback (most recent call last):
  File "C:\temp\AESZipFileNoPwordCheck.py", line 81, in <module>
    my_secrets = zf.read(zf.namelist()[0])
  File "C:\Program Files\Python38\lib\site-packages\pyzipper\zipfile.py", line 1964, in read
    return fp.read()
  File "C:\Program Files\Python38\lib\site-packages\pyzipper\zipfile.py", line 1369, in read
    buf += self._read1(self.MAX_N)
  File "C:\Program Files\Python38\lib\site-packages\pyzipper\zipfile.py", line 1467, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
```

**Comment by danifus** [comment]
Hmmm... not sure what is wrong at the moment. Can you try 7z's graphical test feature? https://superuser.com/a/193294

That can give more detailed analysis of the file

**Comment by zdenop** [comment]
![image](https://user-images.githubusercontent.com/574156/88766954-347bd480-d179-11ea-8b2b-c88df4dda816.png)

**Comment by zdenop** [comment]
I turn out that there was wrong password...
